version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./.docker/apache-php-composer.Dockerfile
    image: devenv/laravel
    container_name: devenv_backend
    ports:
      - 80:80
    volumes:
      - ./backend:/backend
    networks:
      - my_app_net
  mysql:
    image: mysql:latest
    container_name: devenv_mysql
    ports:
      - 13306:3306
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my_app_net
    command: mysqld --default-authentication-plugin=mysql_native_password
networks:
  my_app_net:
    driver: bridge
