version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./.docker/apache-php-composer.Dockerfile
    image: devenv/laravel
    container_name: devenv_backend
    ports:
      - 80:80
    volumes:
      - ./backend:/backend
    environment:
      DB_HOST: '127.0.0.1'
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: '123'
  mysql:
    image: mysql:latest
    container_name: devenv_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: '123'
